Xenon/Core/XGPU/XGPU.cpp

- It is now possible to switch VSYNC by pressing the F5 button
- Minor XGPU changes
VSYNC ON:
VSYNC OFF:

GPU: Switchable VSYNC & Minor Changes

---

.gitmodules
CMakeLists.txt
Xenon/Base/Config.cpp
Xenon/Base/Config.h
Xenon/Base/Path_util.cpp
Xenon/Base/Path_util.h
Xenon/Core/XGPU/XGPU.cpp
Xenon/Core/XGPU/XGPU.h
Xenon/Xe_Main.cpp
third_party/CMakeLists.txt

Basic configuration system.
The `Xenon.toml` file contains the settings
It is stored in `{Xenon executable}/Xenon/Xenon.toml`
At the moment, changing the resolution is broken and fullscreen does not work (This is not due to the implementation but to problems with SDL3)

Basic Configuration System

---

Xenon/Core/XCPU/PostBus/PostBus.cpp
Xenon/Core/XGPU/XGPU.cpp

Fixes resolution change in configuration

Difference between window size and internal resolution

---

Xenon/Base/Config.cpp
Xenon/Base/Config.h
Xenon/Core/XGPU/XGPU.cpp
Xenon/Xe_Main.cpp

This PR fixes fullscreen mode and adds some changes to XGPU.

Fix Fullscreen Mode & Minor XGPU Changes

---

Xenon/Base/Config.cpp
Xenon/Base/Config.h
Xenon/Core/RootBus/HostBridge/PCIBridge/SMC/SMC.cpp
Xenon/Core/RootBus/HostBridge/PCIBridge/SMC/SMC.h
Xenon/Xe_Main.cpp

I'm not sure where you want getFuses to be handled, so creating a draft, but otherwise, it should be fine.

Fix some spelling mistakes, and add some QoL improvements

---

.gitignore
Xenon/Base/Config.cpp
Xenon/Base/Config.h
Xenon/Core/RootBus/HostBridge/PCIBridge/ODD/ODD.cpp
Xenon/Core/RootBus/HostBridge/PCIBridge/ODD/ODD.h
Xenon/Core/XCPU/Interpreter/PPCInterpreter.cpp
Xenon/Core/XCPU/PPU/PPU.cpp
Xenon/Core/XCPU/PPU/PPU.h
Xenon/Core/XGPU/XGPU.cpp
Xenon/Core/XGPU/XGPU.h
Xenon/Xe_Main.cpp

Allows for window resizing on the fly, and config changing for size.

[XGPU/Config]: Adjust code to allow for resizing, and config option

---

third_party/CMakeLists.txt

Remove TOML11 Warnings

---

Xenon/Base/LRUCache.h
Xenon/Core/XCPU/Interpreter/PPCInterpreter.cpp
Xenon/Core/XCPU/Interpreter/PPCInterpreter.h
Xenon/Core/XCPU/Interpreter/PPC_MMU.cpp
Xenon/Core/XCPU/Interpreter/PPC_System.cpp
Xenon/Core/XCPU/PPU/PPU.cpp
Xenon/Core/XCPU/PPU/PowerPC.h
Xenon/Core/XCPU/Xenon.cpp
Xenon/Render/GUI/GUI.cpp
Xenon/Render/GUI/Implementations/OpenGL.cpp
Xenon/Render/GUI/Implementations/OpenGL.h

* Cleaned up some code
* Impl'd new debugger
* Update CPI formula to be constexpr
*
Closes the following branches:
* linux-tests
* debug-impl
* interpreter-refactor

[Dbg] [PPU] Add new Debug UI, update PPU CPI

---

Xenon/Base/Config.cpp

[Xenon/Config.cpp] Add address list for hardware skip

---

Xenon/Core/XCPU/Interpreter/PPCOpcodes.h
Xenon/Core/XCPU/Interpreter/PPC_LS.cpp

Implementation of `lhaux` according to IBM documentation.

[PPC_LS] Implement `lhaux`

---

Xenon/Core/XCPU/Interpreter/PPCOpcodes.h
Xenon/Core/XCPU/Interpreter/PPC_ALU.cpp
Xenon/Core/XCPU/Interpreter/PPC_LS.cpp

Implementation of `lwaux` according to IBM documentation.

[PPC_LS] Implement `lwaux`

---

Xenon/Core/XCPU/Interpreter/PPCOpcodes.h
Xenon/Core/XCPU/Interpreter/PPC_VXU.cpp

Implementation of `vandc` according to IBM documentation.

[PPC_VXU] Implement `vandc`

---

Xenon/Core/XCPU/Interpreter/PPCOpcodes.h
Xenon/Core/XCPU/Interpreter/PPC_VXU.cpp

Implementation of `vnor` according to IBM documentation.

[PPC_VXU] Implement `vnor`

---

Xenon/Core/XCPU/Interpreter/PPCOpcodes.h
Xenon/Core/XCPU/Interpreter/PPC_VXU.cpp

Implementation of `vxor` according to IBM documentation.

[PPC_VXU] Implement `vxor`

---

Xenon/Core/XCPU/Interpreter/PPCOpcodes.h
Xenon/Core/XCPU/Interpreter/PPC_LS.cpp

Implementation of `stfdx` according to IBM documentation.

[PPC_LS] Implement `stfdx`

---

Xenon/Core/Xe_Main.cpp
Xenon/Core/Xe_Main.h
Xenon/Render/Abstractions/Renderer.cpp
Xenon/Render/Abstractions/Renderer.h
Xenon/Render/OGLRenderer.cpp
Xenon/Render/OGLRenderer.h

Window management is only valid on the main thread in macOS

Move SDL Window init to main thread

---

CMakeLists.txt
Xenon/Render/Dummy/DummyShader.cpp
Xenon/Render/Dummy/DummyShader.h
Xenon/Render/Dummy/Factory/DummyShaderFactory.cpp

Gets dummy backend to actually work without crashing.

DummyShader

---

Xenon/Core/XCPU/Interpreter/PPCOpcodes.h
Xenon/Core/XCPU/Interpreter/PPC_LS.cpp

Implementation of `stfsux` according to IBM documentation.

[PPC_LS] Implement `stfsux`

---

Xenon/Core/XCPU/Interpreter/JIT/x86_64/JITEmitter_ALU.cpp
Xenon/Core/XCPU/Interpreter/PPCOpcodes.h

- Implementation of `andx`
- Update of asmjit

[JIT_ALU] Implement `andx`

---

Xenon/Core/XCPU/Interpreter/JIT/x86_64/JITEmitter_ALU.cpp
Xenon/Core/XCPU/Interpreter/PPCOpcodes.h

[JIT_ALU] Implement `xor`

---

Xenon/Core/XCPU/Interpreter/JIT/x86_64/JITEmitter_ALU.cpp
Xenon/Core/XCPU/Interpreter/PPCOpcodes.h

JIT implementation of `mulld` and `or`

[JIT_ALU] Implement `mulld` and `or`

---

Xenon/Core/XCPU/Interpreter/JIT/x86_64/JITEmitter_ALU.cpp
Xenon/Core/XCPU/Interpreter/PPCOpcodes.h

[JIT_ALU] Implement `nandx`

---

Xenon/Core/XCPU/JIT/PPU_JIT.cpp
Xenon/Core/XCPU/JIT/PPU_JIT.h
Xenon/Core/XCPU/JIT/x86_64/JITEmitter_ALU.cpp
Xenon/Core/XCPU/JIT/x86_64/JITEmitter_Helpers.h
xenon.nix

Update Asmjit to 1.18.
PS: I don't know how to update nix packages

Update Asmjit to 1.18
